id: github_total
title: Github 总下载量
icon: Github
description: KWDB 的 Github 总下载量
queryModule: githubTotal
viz: stat
section: total_downloads
order: 25
colSpan: 1
options:
  decimals: 0
  suffix: ''
defaultTimeRange:
  from: now-30d
  to: now
refreshSec: 60
